refactor: remove "owner" and other default permissions / groups
reactioncommerce/reaction pull request #6063
Opened 2020-01-29 22:46 UTC by kieckhafer

Resolves #6030   
Impact: **breaking|major**  
Type: **feature|refactor*

## Issue
We'd like to move away from the all encompassing "owner" role.

## Solution
- remove the code which adds users to an "owner" role when creating an account (https://github.com/reactioncommerce/reaction/commit/0df8f2ed61ecd350115e7ede635ee30444448376)
- remove code which adds user to "customer" role when creating a non-owner account, users no longer are required to be in a group (https://github.com/reactioncommerce/reaction/commit/0bdc5dbe5d418b64c53fe08f01fc8d64156926dc)

## Breaking changes
[WIP]

## Testing

2020-01-30 00:07 UTC, kieckhafer commented
@aldeed overall I think this is good for a look. Two places I wasn't 100% sure what to do:

1. I don't think anyone is going to have anonymous anymore, can we remove this? https://github.com/reactioncommerce/reaction/blob/refactor-removeOwner/src/core-services/cart/mutations/reconcileCarts.js#L48:L48
1. I think you mentioned in another PR we might not even use this anymore? Can this be removed? https://github.com/reactioncommerce/reaction/blob/refactor-removeOwner/src/plugins/notifications/util/sendNewOrderNotifications.js#L57:L57

2020-01-30 00:47 UTC, aldeed commented
@kieckhafer Both of those code areas will be gone if you merge in `release-3.0.0`. I had removed them in https://github.com/reactioncommerce/reaction/pull/6056, which is merged now.

2020-01-30 01:11 UTC, aldeed requested changes
@kieckhafer Looks like you hit everything in the list here. I left a few suggestions, and I'll do some more testing before we merge this.

2020-01-30 01:11 UTC, aldeed commented on src/core-services/account/mutations/createAccount.js
> +  const appAccounts = await Accounts.find({}).toArray();
This would definitely be a very slow query and probably crash after a certain number of accounts. I've found the fastest way is:

```js
const anyAccount = await Accounts.findOne();
if (!anyAccount) {
}
```

There is also `find().count()` but we don't need an accurate count in this case and supposedly count can sometimes be very slow, too.

2020-01-30 01:11 UTC, aldeed commented on src/core-services/account/mutations/createAccount.js
> +    const systemManagerGroup = await Groups.findOne({ slug: "system-manager" });
On this and the accounts manager one, you could add `{ projection: { _id: 1 } }` as the second arg to optimize a bit.

2020-01-30 01:11 UTC, aldeed commented on src/core-services/account/mutations/createAccount.js
> +      });
Given the amount of code here and the fact that we perhaps will need to do this from other places, I'd create two util functions, `createSystemManagerGroup` and `createAccountsManagerGroup`, and call them here.

2020-01-30 01:11 UTC, aldeed commented on src/core-services/account/mutations/createAccount.js
> +      });
Or perhaps `ensureSystemManagerGroup`, which would also do the check for existence and return the ID either way.

2020-01-30 01:11 UTC, aldeed commented on src/core-services/account/mutations/createAccount.js
> +    const accountsManagerGroup = await Groups.findOne({ slug: "system-manager" });
Should be "accounts-manager" slug.

2020-01-30 01:11 UTC, aldeed commented on src/core-services/account/mutations/createAccount.js
> +  if (appAccounts) {
Just use `else`?

2020-01-30 01:11 UTC, aldeed commented on src/core-services/account/util/canAddAccountToGroup.js
> +  const hasPermissionToAddAccountToGroup = await userHasPermission("reaction:legacy:groups", "manage:accounts", { shopId });
At this point, should we just delete this fn and pass these same args to `validationPermissions` in the two fns that call this one? More of the standard pattern.

2020-01-30 01:11 UTC, aldeed commented on src/core-services/account/util/defaultRoles.js
> -  ...defaultCustomerRoles,
I'd say delete `reaction:legacy:shops/owner` and `owner` from the `defaultOwnerRoles` list. Just accounts mgmt plus shop create for now.

2020-01-30 23:21 UTC, kieckhafer commented
@aldeed addressed all your comments, and made a few more changes regarding global permission in `permissionsByUserId`

2020-01-31 16:26 UTC, aldeed approved these changes

2020-01-31 16:27 UTC, merged