refactor: move payments-example plugin to npm package
reactioncommerce/reaction pull request #6142
Opened 2020-03-04 18:19 UTC by trojanh

Resolves https://github.com/reactioncommerce/reaction/issues/6129
Impact: **minor**
Type: **refactor**

## Issue
Convert the payments-example plugin in npm package. This includes moving all related files into a new repository, releasing that repo as an npm package, and then updating this repo, reaction, to use the npm version of the plugin.

plugin => https://github.com/reactioncommerce/plugin-payments-example/pull/1

## Testing
Check if all the `payments-example` plugin api are visible and working like before

2020-03-09 23:02 UTC, kieckhafer requested changes

2020-03-09 23:02 UTC, kieckhafer commented on docker-compose.dev.yml
> +    - /Users/kiprosh/projects/reaction-payments-example/plugin-payments-example
This should not be committed.

2020-03-09 23:02 UTC, kieckhafer commented on jest.config.cjs
> +const externalNodeModules.join("|") = [
👍 Nice, been trying to think of the best way to lay this out so it doesn't get so crowded.

2020-03-09 23:02 UTC, kieckhafer commented on src/registerPlugins.js
> +import registerExamplePaymentsPlugin from "@reactioncommerce/plugin-payments-example";
Please alphabetize this list.

2020-03-10 13:33 UTC, trojanh commented on docker-compose.dev.yml
> +    - /Users/kiprosh/projects/reaction-payments-example/plugin-payments-example
yeah, sorry I did this by mistake.

2020-03-10 13:46 UTC, trojanh commented
Thanks for reviewing @kieckhafer , I have made the suggested changes, please review it when you get a chance.

2020-03-10 17:03 UTC, trojanh commented
@kieckhafer just noticed that jest node modules need to alphabetized as well, so pushing that change now

2020-03-10 17:04 UTC, kieckhafer commented
@trojanh Thanks! I was about to comment on that, glad you caught it.

2020-03-10 17:06 UTC, trojanh commented
sure @kieckhafer , fixed that now

2020-03-10 17:12 UTC, kieckhafer commented
@trojanh now that your other package is published, can you run `npm install` locally, and then push the new `package-lock.js` that is created. I think that'll solve the CI issues.

2020-03-10 17:37 UTC, kieckhafer requested changes

2020-03-10 17:37 UTC, kieckhafer commented on jest.config.cjs
> +    `node_modules/(?!(${externalNodeModules.join("|")}/)`
You need to add a parens to the end of this, that should fix the test issues.

```suggestion
    `node_modules/(?!(${externalNodeModules.join("|")})/)`
```

2020-03-10 18:12 UTC, kieckhafer approved these changes

2020-03-10 18:13 UTC, kieckhafer commented
This is ready to go once https://github.com/reactioncommerce/plugin-payments-example has been made public.

2020-03-10 18:13 UTC, merged