fix: variant clone produces null and undefined values
reactioncommerce/reaction pull request #6149
Opened 2020-03-13 22:28 UTC by mikemurray

Resolves #6148 
Impact: **critical**
Type: **bugfix**

## Issue

Cloning a variant with that has missing values for title, optionTitle, length, width, height, and weight, would produce `null` values in the database. This breaks the API.

## Solution

Ensure the values valid before inserting them into the database.

## Breaking changes

none

## Testing
1. Use the reaction admin
2. Clone a variant with options, but don't fill out the fields `title, optionTitle, length, width, height, and weight`
3. Ensure everything clones correctly
4. Now fill out the missing values and clone a variant that has options
5. See everything clones correctly

2020-03-14 00:53 UTC, willopez requested changes
Cloning variants now works correctly. However, it's not possible to set the price on a variant. When I set the price and click "Save changes" the prices gets cleared out to an empty string.

2020-03-18 17:15 UTC, mikemurray commented
@willopez I don't think this PR is the ultimate cause of these issues. In the Reaction Admin, I'm seeing missing `price/compareAtPrice` from the product GQL fragment.

I'm also noticing that the price field for variants with options is an `object` and not `float` to represent the price range. This is a bigger problem because a field in GQL is changing between two different types.

2020-03-18 17:20 UTC, mikemurray commented
@willopez Added a ticket about the price issue: https://github.com/reactioncommerce/reaction/issues/6152

2020-03-18 17:47 UTC, willopez commented
@mikemurray as discussed, we'll handle that issue in a separate PR.

2020-03-18 17:47 UTC, willopez approved these changes
LGTM

2020-03-18 17:47 UTC, merged