Update @reactioncommerce dependencies
reactioncommerce/reaction pull request #6296
Opened 2020-10-12 11:29 UTC by loan-laux

Signed-off-by: Loan Laux <loan@outgrow.io>

Impact: **minor**
Type: **chore**

## Issue
`@reactioncommerce/api-plugin-accounts` and `@reactioncommerce/api-plugin-authorization-simple` are outdated.

## Solution
Update the packages to their latest versions.

## Breaking changes
None.

2020-10-12 12:52 UTC, mpaktiti requested changes
Thank you for this @loan-laux! I left a couple of comments regarding the semver ranges.

2020-10-12 12:52 UTC, mpaktiti commented on package.json
> +    "@reactioncommerce/api-plugin-accounts": "^1.5.0",
Can you change this to use a tilde `~` range like the rest?

2020-10-12 12:52 UTC, mpaktiti commented on package.json
> +    "@reactioncommerce/api-plugin-authorization-simple": "^1.3.1",
Same as above, we should use a tilde range like the rest of the dependencies.

2020-10-14 08:15 UTC, loan-laux commented
Thanks for catching that @mpaktiti. I'm used to using `^` on other projects so I didn't think of looking what you were using in the `package.json`. Should be all good now!

2020-10-14 10:08 UTC, mpaktiti approved these changes

2020-10-14 10:09 UTC, merged

2020-10-15 09:33 UTC, loan-laux commented
Thanks @mpaktiti. Would be amazing if we could get a minor release for this one!