Emitting afterAddTagsToProducts, afterTagDelete, afterRemoveTagsFromProducts
reactioncommerce/reaction pull request #6541
Opened 2022-10-03 15:40 UTC by vishalmalu

Impact: minor
Type: feature

**Issue**
This PR emits following additional events when respective mutations have been executed.

- afterAddTagsToProducts
- afterRemoveTagsFromProducts
- afterTagDelete

2022-10-03 17:04 UTC, tedraykov requested changes
Please run `changeset` on `npx changeset` to generate the changelog files. This is required to bump the plugin versions.
Apart from that the PR is good to go.

2022-10-04 01:35 UTC, vishalmalu commented
@tedraykov I've added changeset.

2022-10-04 06:56 UTC, zenweasel requested changes

2022-10-04 06:56 UTC, zenweasel commented on packages/api-plugin-products/src/mutations/addTagsToProducts.js
> +  const { appEvents } = context;
You are already deconstructing context on line 16, should probably just get `appEvents` from there.

2022-10-04 06:56 UTC, zenweasel commented on packages/api-plugin-products/src/mutations/removeTagsFromProducts.js
> +  const { appEvents } = context;
Same comment re: context as above

2022-10-06 09:00 UTC, tedraykov approved these changes

2022-10-07 07:32 UTC, zenweasel approved these changes

2022-10-07 07:32 UTC, merged