feat: set default ff-type for shop
reactioncommerce/reaction pull request #6543
Opened 2022-10-04 11:35 UTC by sujithvn

Signed-off-by: Sujith <mail.sujithvn@gmail.com>

Resolves #6474 
Impact: **major**
Type: **feature**

## Issue

Admin should be able to define what available fulfillment types should be added by default to new products(#6474)
User should be able to check a box in the admin on any/all/none of the fulfillment types and those would automatically be added to new products as they are created. THIS SHOULD NOT AFFECT EXISTING PRODUCTS AT ALL

## Solution

Current available FF-types can be retrieved using the query `getFulfillmentTypes` and presented to user. User can select one/all/none of the ff-types and use the `updateShopSettings` mutation to update the same.

While creating a new Product, the `supportedFulfillmentTypes` in the input (if provided) will be added to the default ff-types from the shop settings and used for creating new product.

## Breaking changes
None. If there are no ff-types added then no entries are added to product.  User input will be retained as it is.

## Testing
1. use the `updateShopSettings` mutation to update the default ff-types for shop.
2. new products created will include the default ff-type from shop settings 
3. use the `updateShopSettings` mutation to remove any of the default ff-types for shop.
4. new products created will contain only user input ff-types

2022-10-07 08:09 UTC, zenweasel approved these changes

2022-10-07 08:10 UTC, zenweasel commented
@sujithvn Please correct your branches on this and other PR's

2022-10-13 02:00 UTC, aldeed requested changes

2022-10-13 02:00 UTC, aldeed commented on packages/api-plugin-products/src/mutations/createProduct.js
> +  combinedSupportedFulfillmentTypes = [...new Set(combinedSupportedFulfillmentTypes)];
This seems wrong. If a product has `supportedFulfillmentTypes` supplied when creating it, wouldn't you want to keep that as is? I would think it would just be:

```js
supportedFulfillmentTypes: initialProductData.supportedFulfillmentTypes || defaultFulfillmentTypesForShop || []
```

If the intention is to _force_ every produce to support these, then another prefix like `base` or `global` might be a better name than `default` for the setting.

2022-10-13 02:00 UTC, aldeed commented on packages/api-plugin-fulfillment/src/index.js
> +              optional: true
Optional on the item schema would mean a sparse array (with nulls allowed) so `"defaultFulfillmentTypesForShop.$": String` is probably better.

2022-10-13 04:08 UTC, sujithvn commented on packages/api-plugin-products/src/mutations/createProduct.js
> +  combinedSupportedFulfillmentTypes = [...new Set(combinedSupportedFulfillmentTypes)];
@aldeed 
Yes, my intention was to add the user provided `supportedFulfillmentTypes` to the `base` entries defined for the Shop. But either of them could be undefined. That is the reason I did so.
As you mentioned, `base` would be a better name than `default` in the shopSettings.

2022-10-13 04:09 UTC, sujithvn commented on packages/api-plugin-fulfillment/src/index.js
> +              optional: true
Ok, removing the `optional`

2022-11-17 11:43 UTC, aldeed approved these changes

2022-11-22 02:56 UTC, vanpho93 approved these changes

2022-12-08 20:20 UTC, aldeed approved these changes

2023-05-18 18:04 UTC, sujithvn commented
This PR is replaced by the commit `df5ed5e2f8ef9509490c2e90af20f9b80f439773` on  branch `00-fulfillment-base`

2023-05-18 18:04 UTC, closed without merging