Initial i18n for Fulfillment
reactioncommerce/reaction pull request #6545
Opened 2022-10-05 10:58 UTC by sujithvn

Signed-off-by: Sujith <mail.sujithvn@gmail.com>

Resolves #6473 
Impact: **minor**
Type: **feature**

## Issue

There are no localised versions of customer or admin facing messages.

## Solution

Created i18n config files for the newly introduced plugins. 

The required files for two of the below mentioned plugins were completely copied over from old plugin. 
`api-plugin-fulfillment-type-shipping` (copied over from `api-plugin-shipments`)
`api-plugin-fulfillment-method-shipping-flat-rate` (copied over from `api-plugin-shipments-flat-rate`)

Added new config files for remaining 4 plugins below
`api-plugin-fulfillment`
`api-plugin-fulfillment-type-pickup`
`api-plugin-fulfillment-method-pickup-store`
`api-plugin-fulfillment-method-shipping-ups`

## Breaking changes
None

## Testing
Need to co-ordinate with the Front-end team to understand if there are any additional entries required in the config-files for the new plugins.

2022-10-31 07:00 UTC, zenweasel requested changes
I think one copypasta mistake

2022-10-31 07:00 UTC, brent-hoover commented on packages/api-plugin-fulfillment-method-pickup-store/src/i18n/en.json
> +          "noUPSRatesFound": "No Store pickup fulfillment methods found"
Why is this called "noUPSRatesFound"? In the other files it's just called noRatesFound

2022-10-31 07:00 UTC, brent-hoover commented on pnpm-lock.yaml
> -      '@snyk/protect': 1.1017.0
Probably best to just remove this

2022-11-02 02:37 UTC, sujithvn commented on packages/api-plugin-fulfillment-method-pickup-store/src/i18n/en.json
> +          "noUPSRatesFound": "No Store pickup fulfillment methods found"
Changed to a common key `noRatesFound` in 2 plugins (shipping-dynamic-rate and pickup-store). Matches with what we have in shipping-flat-rate

2022-12-08 19:20 UTC, aldeed approved these changes

2022-12-09 10:28 UTC, vanpho93 approved these changes

2023-05-18 18:02 UTC, sujithvn commented
This PR is replaced by the commit `7503a643cc7a496faf1c31aca8922611057e20e2` on  branch `00-fulfillment-base`

2023-05-18 18:02 UTC, closed without merging