feat: promotion framework with coupons
reactioncommerce/reaction pull request #6552
Opened 2022-10-12 02:33 UTC by vanpho93

Resolves #6443
Impact: major
Type: feature

## Issue

Currently, there is no explicit promotion in the framework so we need to check if it works.

## Solution

Adding coupon as new type of promotion to see how it works with current promotion framework

2022-10-13 10:32 UTC, zenweasel requested changes
Looking really good. Just a few minor comments

2022-10-13 10:32 UTC, brent-hoover commented on packages/api-plugin-promotions-coupons/src/triggers/couponsTriggerHandler.js
> + * @summary a no-op function for testing of promotions
Copy-pasta Summary

2022-10-13 10:32 UTC, brent-hoover commented on packages/api-plugin-sample-data/src/loaders/loadPromotions.js
> +  label: "15 percent off your entire order when you spend more then $100",
So this description is confusing. Coupons don't usually have a separate condition and are these being enforced?

2022-10-13 10:32 UTC, brent-hoover commented on packages/api-plugin-promotions-coupons/src/mutations/applyCouponToCart.js
> +  const now = new Date();
One thing to think about here (and everywhere we are doing date/time comparisons) is that this is going to be server time which is generally going to be GMT which means that a coupon would expire 8 hours earlier than it should which is going to make people angry. We probably need to have the user set a timezone to use and use that everywhere.

2022-10-14 08:09 UTC, vanpho93 commented on packages/api-plugin-promotions-coupons/src/mutations/applyCouponToCart.js
> +  const now = new Date();
I think we should have only one strict end time for promotions, but showing that time on UI should change regard user timezones. If we do the comparisons base on user timezones, they may change timezone setting to be able to use the expired promotion?

2022-10-14 08:11 UTC, zenweasel commented on packages/api-plugin-promotions-coupons/src/mutations/applyCouponToCart.js
> +  const now = new Date();
By user I mean our customer, the person creating the promotion, not the consumer. Should have been more clear.

2022-10-14 08:25 UTC, vanpho93 commented on packages/api-plugin-promotions-coupons/src/mutations/applyCouponToCart.js
> +  const now = new Date();
It seems to me this is a common front end task.
They can get the current timezone add it to date time input like this `+10:00` inside `new Date("2022-10-14T08:12:39.584+10:00")`.

2022-10-14 09:40 UTC, zenweasel commented on packages/api-plugin-promotions-coupons/src/mutations/applyCouponToCart.js
> +  const now = new Date();
I think you still don't understand what I am saying

2022-10-14 09:40 UTC, merged