New fulfillment impacted plugins
reactioncommerce/reaction pull request #6615
Opened 2022-11-03 13:36 UTC by sujithvn

Signed-off-by: Sujith mail.sujithvn@gmail.com

Resolves #6471 
Impact: **breaking**
Type: **feature**

### This PR replaces #6582 

## Issue

In the current system, the only way for order fulfillment is via shipping which is hardcoded into the system. We need to introduce the flexibility for users to add their own fulfillment types via plugins.

## Solution

We are creating a base fulfillment plugin which would enable other fulfillment types (like shipping, pickup, digital) to be introduced via plugins. Each of the newly introduced fulfillment type plugin would need to have the specific fulfillment methods also to be added as separate plugins. Example, fulfillment type 'pickup' could have fulfillment methods like 'store pickup' and 'curb-side pickup'.

This PR is 4th entry (new-fulfillment-impacted-plugins)

## PR Details in order

```
feat/fulfillment-types
 | 
 | __ 00 fulfillment base #6610 
 |        | __ new-fulfillment-type-shipping      #6614
 |        | __ new-fulfillment-type-pickup.    #6613 
 |__ new-fulfillment-impacted-plugins. [carts, products, orders, catalogs]  <--- This PR #6615 
 |__ new-placeOrder refactor #6616 

```
## Existing PRs based on the #6480 (to be updated to point to #6610) 
We shall change the base branch of the 3 existing PRs (i18n #6545, dataMigration #6544, setDefaultFFtype #6543) to  point to 00 fulfillment base

#### Changes in detail:
##### CARTS
* New field - cartVersion in the cart to identify the new carts. Old carts will not have this field
* New field - selectedFulfillmentType: This field allows UI to send the fulfillment-type selected by user for the product while adding to the cart. This is optional and if not selected the item would default to undecided fulfillment group.
* New field - supportedFulfillmentTypes: This field was supposed to be existing but was missing. Added now (bug fix).
* New Mutation - setFulfillmentTypeForItems: Accepts an array of itemIds and a selected fulfillment type along with cart details. This mutation would move all the provided items to the requested fulfillment group depending on conditions like FFtype is supported by product, FFtype is active etc.
* Exported ShippingMethod & Shipment from SimpleSchema - these schemas will be extended in the api-plugin-fulfillment plugin to have the allowedValues changed from the hard coded "shipping" to dynamic array containing all the installed FFTypes
* New field - fulfillmentMethod - This is field will be non-editable and used for matching the fulfillment method from other functions/calls. Matching on existing fields like 'name' which are user-input in flat-rate method is not reliable. 
* New field - displayMessageMethod - This new field will hold any string to be displayed along the FF Method in the UI, example store pickup requesting user to come in only after 24hrs of ordering.
* New field - methodAdditionalData: This could be fulfillment specific information used for processing in the system. Example Store may provide store details.
* updateCartFulfillmentGroups: logic updated - when new item is added to cart, if "selectedFulfillmentType" is provided, we add to that group, else the item goes to "Undecided" group.

##### CATALOGS
* supportedFulfillmentTypes - this field will be extended in the api-plugin-fulfillment plugin to have the allowedValues changed from the hard coded "shipping" to dynamic array containing all the installed FFTypes

##### PRODUCTS
* supportedFulfillmentTypes - this field will be extended in the api-plugin-fulfillment plugin to have the allowedValues changed from the hard coded "shipping" to dynamic array containing all the installed FFTypes

##### ORDERS
* Exported CommonOrder, orderFulfillmentGroupInputSchema, SelectedFulfillmentOption - these schemas will be extended in the api-plugin-fulfillment plugin to have the allowedValues changed from the hard coded "shipping" to dynamic array containing all the installed FFTypes
* New field - methodAdditionalData: This could be fulfillment specific information used for processing in the system. Example Store may provide store details.
(above 2 changes are spread across multiple files)

##### Integration Tests updated
* Updated the integration tests to match the changes in plugins.

## Breaking changes

Since this is the new way of handling fulfillment, the existing shipment plugins would not work along with this. User would need to migrate the data (migration script will be developed) and remove the shipment plugins (api-plugin-shipments and api-plugin-shipments-flat-rate).

## Testing
All this is new code and at this stage this is not integrated to reaction, meaning the plugins.json is not updated to include this plugin. Hence proper testing can be carried out only after merging in the remaining PRs.

2022-11-20 13:23 UTC, vanpho93 commented on apps/reaction/package.json
> -    "@reactioncommerce/api-core": "2.0.1",
This seems wrong. New dep versions are downgrades from the old ones?

2022-11-20 13:23 UTC, vanpho93 commented on packages/api-plugin-carts/src/util/updateCartFulfillmentGroups.js
> +    if (group.itemIds && group.itemIds.includes(itemId) && shopId === group.shopId) {
This can work too.

```suggestion
    if (group.itemIds?.includes?.(itemId) && shopId === group.shopId) {
```

2022-11-20 13:23 UTC, vanpho93 commented on packages/api-plugin-carts/src/util/updateCartFulfillmentGroups.js
> +  return removeFromGroups || null;
`|| null` is redundant. 

```suggestion
  return _.compact(removeFromGroups);
```

2022-11-20 13:23 UTC, vanpho93 commented on packages/api-plugin-carts/src/util/updateCartFulfillmentGroups.js
> +  }
I think there are many redundant null checks.
There is no need to reassign `removeFromGroups`, for each is enough.
```suggestion
  const removeFromGroups = determineRemoveFromGroups(currentGroups, item._id, item.shopId);
removeFromGroups.forEach((group) => {
  group.itemIds = _.pull(group.itemIds, "itemId");
});
```

2022-11-20 13:23 UTC, vanpho93 commented on packages/api-plugin-carts/src/util/updateCartFulfillmentGroups.js
> +  }
```suggestion
addToGroup.itemIds = _.uniq([...addToGroup.itemIds || [], item._id]);
```

2022-11-20 13:23 UTC, vanpho93 commented on packages/api-plugin-carts/src/util/updateCartFulfillmentGroups.js
> +    if (selectedFulfillmentType && !supportedFulfillmentTypes.includes(selectedFulfillmentType)) {
Should create a separate function to avoid too many if else and long function.

```js
const normalizeSelectedFulfillmentType = (selectedFulfillmentType) {
  if (_.isNil(selectedFulfillmentType)) {
    const hasOnlyOneSupportedFulfillmentType = supportedFulfillmentTypes.length === 1;
    if (hasOnlyOneSupportedFulfillmentType) return _.first(supportedFulfillmentTypes);
   return "undecided";
  }
  if(!supportedFulfillmentTypes.includes(selectedFulfillmentType)) {
    throw new ReactionError("not-found", "Selected fulfillmentType is not supported by the Product");
  }
  return selectedFulfillmentType;
}
```

2022-11-20 13:23 UTC, vanpho93 commented on packages/api-plugin-carts/src/util/updateCartFulfillmentGroups.js
> +    let enabledFulfillmentTypes = (enabledFulfillmentTypeObjs || []).map((ffType) => ffType.fulfillmentType);
Try to avoid `let`.

```suggestion
    const enabledFulfillmentTypes = enabledFulfillmentTypeObjs.map((ffType) => ffType.fulfillmentType).filter((type) => _.isString(type));
```

2022-12-08 20:03 UTC, aldeed requested changes
See a few suggestions, but overall this seems on the right track. I am not sure I like the "undecided" group. What if someone registers a fulfillment type plugin with the name "undecided"? If this ability is necessary, you could make the `group.type` field optional and have `null` mean undecided. But it seems like the best approach would be to have a required shop default and use that.

2022-12-08 20:03 UTC, aldeed commented on packages/api-plugin-carts/src/schemas/cart.graphql
> +  items: [String]!
`itemIds` would be a clearer name

2022-12-08 20:03 UTC, aldeed commented on packages/api-plugin-carts/src/simpleSchemas.js
> +  },
I believe `fulfillmentMethod` is sort of a subtype, corresponding with the providing package (e.g. flat rate vs dynamic rate, but both are "shipping" type). The problem is that the project already uses the term "method" for individual methods, so it seems confusing. I think some other ecommerce platforms use `fulfillmentProvider`, and that makes more sense to me. @zenweasel

2022-12-08 20:03 UTC, aldeed commented on packages/api-plugin-carts/src/simpleSchemas.js
> +    allowedValues: ["undecided"], // extended with dynamic values in fulfillment plugin startup
Another option would be to have fulfillment plugins include an array in their plugin registration options:

```js
{
  fulfillmentTypes: ["shipping"]
}
```

Then use `registerPluginHandler` in this cart plugin to read all of the `plugin.fulfillmentTypes` and add them all to `allowedValues` in the schema. That way all cart schema changes will happen in the cart plugin, which makes the most sense to me.

Something similar is how payment methods, address validation methods, etc. are registered from individual plugins.

2022-12-08 20:03 UTC, aldeed commented on packages/api-plugin-carts/src/util/updateCartFulfillmentGroups.js
> +    const enabledFulfillmentTypeObjs = await Fulfillment.find({ "shopId": item.shopId, "provider.enabled": true }).toArray();
It seems like you could add `fulfillmentType: selectedFulfillmentType` to the query object and use `findOne` instead of `find().toArray()`. Then you don't need to do any of the array mapping and checking in code and the db operation will be faster.

2023-05-18 08:09 UTC, merged