feat: add price type for product
reactioncommerce/reaction pull request #6696
Opened 2022-12-09 02:08 UTC by vanpho93

Resolves #6638
Impact: **major**
Type: **feature**

Basically this is used to include or exclude items that are on sale or on clearance.

Stock price types are:

full - (not MSRP, but not discounted)
clearance - Permanently marked down to move
sale - Temporarily on sale (e.g. Black Friday or Mother's Day sale) but return to full price

2022-12-12 04:01 UTC, zenweasel requested changes

2022-12-12 04:01 UTC, brent-hoover commented on packages/api-plugin-pricing-simple/src/schemas/schema.graphql
> +  priceType: String
The comment says "the price" but it is not the price

2022-12-12 04:01 UTC, brent-hoover commented on pnpm-lock.yaml
>        graphql: 14.7.0
It would probably be a good habit to get into to not include these Snyk updates as they will catch you with merge conflicts at some point

2022-12-12 04:01 UTC, brent-hoover commented on packages/api-plugin-pricing-simple/src/util/publishProductToCatalog.js
> +    priceType: doc.priceType
This mutation would cause the priceType to be published to the catalog, but I don't see where it would be added to the cart. I think (but not sure) that the mutation is [here](https://github.com/reactioncommerce/reaction/blob/f796e252ef1f8a72ce5b8ea566a6d4172455cd67/packages/api-plugin-carts/src/xforms/xformCartItems.js#L6)

2022-12-14 01:50 UTC, vanpho93 commented on packages/api-plugin-pricing-simple/src/util/publishProductToCatalog.js
> +    priceType: doc.priceType
Added,

```
transforms: [
        {
          name: "addPriceTypeToCartItems",
          fn: addPriceTypeToCartItems,
          priority: 10
        }
      ]
   ```

2022-12-14 09:38 UTC, brent-hoover approved these changes

2022-12-14 09:40 UTC, merged