feat: create standard coupon
reactioncommerce/reaction pull request #6734
Opened 2022-12-29 08:19 UTC by vanpho93

Resolves #6723
Impact: **major**
Type: **feature**

## Solution
Creating the mutation allows the admin can create a standard coupon.

2023-01-03 23:24 UTC, zenweasel commented
Broken unit tests and broken DCO.

Also, I think we should be moving coupon work into a separate feature branch so we can test the existing functionality separately.

2023-01-03 23:34 UTC, zenweasel approved these changes, later dismissed

2023-01-03 23:34 UTC, zenweasel commented on packages/api-plugin-promotions-coupons/src/mutations/createStandardCoupon.test.js
> +test("should insert a new coupon and results created results", async () => {
Not sure what "results created results" means

2023-01-03 23:34 UTC, zenweasel commented on packages/api-plugin-promotions-coupons/src/mutations/createStandardCoupon.test.js
> +    }
Wouldn't hurt to add `calledOnce` expects for findOne and insertOne

2023-01-03 23:34 UTC, zenweasel commented on pnpm-lock.yaml
> +      '@snyk/protect': 1.1080.0
Should probably exclude this?

2023-01-09 09:21 UTC, tedraykov requested changes
Why is the coupon referred to as Standard Coupon? Does that imply there are nonstandard coupons? If the collection name is just `Coupon` do we need to overstate that it is a standard one?

Apart from that the PR looks good.

2023-01-09 09:29 UTC, vanpho93 commented
> Why is the coupon referred to as Standard Coupon? Does that imply there are nonstandard coupons? If the collection name is just `Coupon` do we need to overstate that it is a standard one?

@tedraykov a standard coupon does not require userId so it can be applied by anyone.

2023-01-18 07:53 UTC, tedraykov commented
This can't be implied from the naming alone, but I haven't seen the full specs for the coupons so I'll take it as is.

2023-01-18 07:53 UTC, tedraykov submitted a review, later dismissed

2023-01-30 03:46 UTC, merged