feat: create migration for old discount
reactioncommerce/reaction pull request #6784
Opened 2023-02-08 01:58 UTC by vanpho93

Resolves #6690
Impact: **major**
Type: **feature**

## Issue

Old discount codes will not work in new promotion framework

## Solution

Create migration for carts / discount codes to new promotions / coupons

2023-02-09 01:43 UTC, brent-hoover commented on package.json
> +    "start:dev": "pnpm --filter=reaction run start:dev",
Generally we should not just throw in extra changes unrelated to solving a particular problem. We should try to keep PR's as focused as possible. Not blocking on this one though.

2023-02-09 01:50 UTC, zenweasel requested changes

2023-02-09 01:50 UTC, zenweasel commented on packages/api-plugin-promotions-coupons/migrations/2.js
> +async function incrementSequence(db, shopId, entity) {
We have a function defined in the code already for this, we should not duplicate it here.

2023-02-09 01:50 UTC, zenweasel commented on packages/api-plugin-promotions-coupons/migrations/2.js
> +async function down({ progress }) {
For this to be a proper down, it should reverse the above migration

2023-02-09 01:50 UTC, zenweasel commented on packages/api-plugin-promotions-coupons/migrations/migrationsNamespace.js
> +export const migrationsNamespace = "promotion-coupons";
So I am not seeing the check for version but we need to do that, but ONLY when they have existing discounts created.

2023-02-10 02:37 UTC, vanpho93 commented on packages/api-plugin-promotions-coupons/migrations/2.js
> +async function incrementSequence(db, shopId, entity) {
The defined function is in another plugin, and we only have access to ({ db, progress }) so it's not easy to do.

2023-02-13 07:08 UTC, zenweasel approved these changes

2023-02-13 07:18 UTC, merged