feat: shipping discount
reactioncommerce/reaction pull request #6802
Opened 2023-02-16 09:04 UTC by vanpho93

Resolves #6773 #6767
Impact: **major**
Type: **feature**

Adding shipping discount with an option to prevent using 2 shipping discounts for one shipment.

Loom: https://www.loom.com/share/0ea5076ca3004ae9b1be6b3880a32e86

2023-02-20 00:14 UTC, zenweasel commented on packages/api-plugin-promotions-discounts/src/discountTypes/shipping/applyShippingDiscountToCart.js
> +    stackability: promotion.stackability,
Are we applying the shipping discount to items? Not sure that's how we want to do that

2023-02-20 00:19 UTC, zenweasel reviewed
Seems ok just have some questions:

1. We are taking the discount on the shipping charge, not items right?
2. We are taking the discount only on shipping and not on handling, correct?
3. Have we taken into account when we may have a split shipment (i.e. two items in the shipping array)?

2023-02-20 00:19 UTC, zenweasel commented on packages/api-plugin-promotions-discounts/src/discountTypes/shipping/applyShippingDiscountToCart.js
> +  const total = formatMoney(calculationMethod(discountValue, totalShippingPrice));
This must be available in a util lib somewhere rather than copy-pasting it here?

2023-02-20 02:23 UTC, vanpho93 commented
> Seems ok just have some questions:
> 
> 1. We are taking the discount on the shipping charge, not items right?
> 2. We are taking the discount only on shipping and not on handling, correct?
> 3. Have we taken into account when we may have a split shipment (i.e. two items in the shipping array)?

1. => Yes, on the shipping charge
2. => Do we want to exclude handling? Currently handling get discounted too but I can exclude it
3. => We have it but we aren't able to demo it with the API because we didn't support split shipment in API level

2023-02-20 02:23 UTC, vanpho93 commented on packages/api-plugin-promotions-discounts/src/discountTypes/shipping/applyShippingDiscountToCart.js
> +    stackability: promotion.stackability,
No, we are applying it to shipping only, as it shows on the Loom demo.

2023-02-20 02:45 UTC, zenweasel commented
@vanpho93 Ok, double-checking whether we should discount handling or not, so hold on this.

2023-02-21 00:30 UTC, zenweasel commented
@vanpho93 Clarified with @brendan-shea-pm , discounts should only be taken against shipping, not handling

2023-02-22 00:12 UTC, zenweasel requested changes
Discounts don't display in quotes which is critical

2023-02-27 07:53 UTC, zenweasel commented
@vanpho93 Can we add a shipping discount promotion to the sample data as well?

2023-02-27 09:24 UTC, zenweasel requested changes
Shipping quotes are not updated when a promotion becomes active after the cart already has quotes on it. Brian has identified the problem already and is working on a fix

2023-03-02 10:25 UTC, zenweasel approved these changes
Great work

2023-03-02 10:25 UTC, zenweasel commented on packages/api-plugin-promotions/src/startup.js
> -  await bullQueue.scheduleJob(context, "setPromotionState", "checkForChangedStates", {}, "*/5 * * * *");
It should not be one but since we're going to make it an env-var it can stay.

2023-03-03 02:12 UTC, merged

2023-03-03 02:18 UTC, zenweasel commented
@vanpho93 In the future please wait for all reviewers I've assigned to approve before merging